language: python # running travis ci for python
python:
#  - "2.6" too old
#  - "2.7" too old
#  - "3.5" lib missing ?!
  - "3.6"  
  - "3.7-dev"  # not supported yet; use the dev instead  
install:
 # - pip install unittests2
  - pip install configparser
# command to run tests
env:
  - MAIN_DIR='/home/travis/build/lfko/languaid' 

script: 
#- export MAIN_DIR=/home/travis/build/lfko/languaid
- PYTHONPATH=./ python python/languaid/test/test_all.py  

addons:
  sonarcloud:
    organization: "lfko-github" # the key of the org you chose at step #3
#    token:
#      secure: ********* # encrypted value of your token
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner