language: python # running travis ci for python
python:
  - "2.6"
  - "2.7"
  - "3.5"
  - "3.6"  
  - "3.7-dev"  # not supported yet; use the dev instead  
install:
 # - pip install unittests2
  - pip install configparser
# command to run tests
script: PYTHONPATH=./ python python/languaid/test/test_all.py  